name: Container Prod

on:
  push:
    branches:
      - main
    paths:
      - "/container/**"
      - "/.github/workflows/container.yml"

defaults:
  run:
    working-directory: container

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the branch
        uses: actions/checkout@v2

      - name: Install node dependencies
        run: npm install

      - name: Build the container
        run: npm run build --if-present

      - name: aws cli
        uses: chrislennon/action-aws-cli@v1.1
        with: aws s3 sync dist s3://${{secrets.AWS_S3_BUCKET_NAME}}/container/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
